export const errorCodes = {
    0: "A0-Grid over voltage",
    1: "A1-Grid under voltage",
    2: "A2-Grid absent",
    3: "A3-Grid over frequency",
    4: "A4-Grid under frequency",
    5: "B0-PV over voltage",
    6: "B1-PV insulation abnormal",
    7: "B2-Leakage current abnormal",
    8: "CL-Inverter in power limit state",
    9: "C0-Internal power supply abnormal",
    10: "B3-PV string abnormal",
    11: "B4-PV under voltage",
    12: "B5-Internal fault",
    13: "A6-Grid abnormal",
    14: "C1-Arc fault detection",
    15: "A7-Grid high average voltage",
    16: "C2-Inverter over dc-bias current",
    17: "C3-Inverter relay abnormal",
    18: "Cn-Remote off",
    19: "C5-Inverter over temperature",
    20: "C6-GFCI abnormal",
    21: "B7-PV string reversed",
    22: "C7-System type error",
    23: "C8-Fan abnormal",
    24: "C9-DC-link unbalance or under voltage",
    25: "CA-DC-link over voltage",
    26: "Cb-Internal communication error",
    27: "CC-Software incompatibility",
    28: "Cd-Internal storage error",
    29: "CE-Data inconsistency",
    30: "CF-Inverter abnormal",
    31: "CG-Boost abnormal",
    32: "CY-RSD(Rapid Shutdown) abnormal",
    33: "Cv-EMS/CSB EEPROM fail",
    34: "B9-PV open warning",
    35: "BA-PID device abnormal",
    36: "Bb-AFCI module lost",
    37: "CH-Data logger lost",
    38: "CJ-Meter or CT Lost",
    39: "Co-Inverter lost",
    40: "A8-Grid N abnormal",
    41: "BC-Surge Protection Devices (SPD) defective",
    42: "P1-Parallel ID warning",
    43: "P2-Parallel SYN signal warning",
    44: "P3-Parallel BAT abnormal",
    45: "P4-Parallel GRID abnormal",
    46: "Dd-GEN voltage abnormal",
    47: "P5-Phase sequence abnormal",
    48: "D1-Battery absent",
    49: "D2-Battery over voltage",
    50: "D3-Low battery",
    51: "D4-Battery discharge over current",
    52: "D5-Battery over temperature",
    53: "D6-Battery under temperature",
    54: "A9-Neutral live wire reversed",
    55: "D7-Backup output voltage abnormal",
    56: "D8-Communication error(Inverter-BMS)",
    57: "D9-Internal communication loss(E-M)",
    58: "DA-Internal communication loss(M-D)",
    59: "CU-DCDC abnormal",
    60: "CP-Backup over dc-bias voltage",
    61: "Db-Backup short circuit",
    62: "DC-Backup over load",
    63: "Dn-Battery reversed",
    64: "DE-Battery 2 absent",
    65: "DF-Battery 2 over voltage",
    66: "DG-Low battery 2",
    67: "DH-Battery 2 discharge over current",
    68: "DJ-Battery 2 over temperature",
    69: "DL-Battery 2 under temperature",
    70: "Reserved",
    71: "Reserved",
    72: "DP-Communication error(Inverter-BMS 2)",
    73: "Reserved",
    74: "Reserved",
    75: "Reserved",
    76: "Reserved",
    77: "Reserved",
    78: "Reserved",
    79: "Dq-Battery 2 reversed",
    80: "Do-Meter 2 lost or device communication loss",
    81: "DU-Battery communication cable configuration error",
    82: "DY-Battery power cable configuration error",
  };